---
services:
  authelia:
    extends:
      file: ../compose-security-baseline/hardening.yml
      service: hardened-small
    image: authelia/authelia:latest
    user: 1000:1000
    cpu_shares: 1536
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      traefik_proxy:
      default:
    expose:
      - 9091
    environment:
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ADDRESS=ldaps://freeipa.${DOMAIN}
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE=/run/secrets/ldap_password
      - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE=/run/secrets/authelia_jwt_secret
      - AUTHELIA_NOTIFIER_SMTP_IDENTIFIER=authelia.docker.home.arpa
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/session_secret
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/run/secrets/storage_encryption_key
      - IPV6_LAN_SUBNET
      - IPV6_TRUSTED_WIFI_SUBNET
      - IPV6_WG_SUBNET
      - LAN_SUBNET
      - POSTGRES_PASSWORD
      - SMTP_PASSWORD
      - SMTP_SENDER
      - SMTP_USERNAME
      - TRUSTED_WIFI_SUBNET
      - TZ=Europe/Zurich
      - WG_SUBNET
      - X_AUTHELIA_CONFIG_FILTERS=template
      - X_AUTHELIA_HEALTHCHECK=true
      - X_AUTHELIA_HEALTHCHECK_SCHEME=http
      - X_AUTHELIA_HEALTHCHECK_HOST=localhost
      - X_AUTHELIA_HEALTHCHECK_PORT=9091
      - X_AUTHELIA_HEALTHCHECK_PATH=
    volumes:
      - config:/config
      - /etc/ssl/certs/ca-certificates.crt:/certs/ca-certificates.crt:ro
      - ./config/configuration.yml:/config/configuration.yml
    labels:
      - 'checkmk_monitor=true'
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik_proxy'
      - 'traefik.http.routers.authelia.rule=Host(`authelia.${DOCKER_DOMAIN}`)'
      - 'traefik.http.routers.authelia.entrypoints=https'
      - 'traefik.http.routers.authelia.tls=true'
      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/authz/forward-auth'
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
    secrets:
      - authelia_jwt_secret
      - ldap_password
      - oidc_grafana_client_secret_digest
      - oidc_hmac_secret
      - oidc_jwks_es256_key
      - oidc_jwks_rs256_key
      - session_secret
      - storage_encryption_key

  postgres:
    extends:
      file: ../compose-security-baseline/hardening.yml
      service: postgres
    image: postgres:18
    networks:
      default:
    volumes:
      - postgres:/var/lib/postgresql/
    environment:
      - POSTGRES_DB=authelia
      - POSTGRES_PASSWORD

  redis:
    extends:
      file: ../compose-security-baseline/hardening.yml
      service: redis
    cpu_shares: 1024
    volumes:
      - redis:/data
    networks:
      default:
    expose:
      - 6379

networks:
  traefik_proxy:
    external: true
  default:
    internal: true

volumes:
  redis:
  config:
  postgres:

secrets:
  authelia_jwt_secret:
    file: secrets/authelia_jwt_secret
  ldap_password:
    file: secrets/ldap_password
  oidc_grafana_client_secret_digest:
    file: secrets/oidc_grafana_client_secret_digest
  oidc_hmac_secret:
    file: secrets/oidc_hmac_secret
  oidc_jwks_es256_key:
    file: secrets/oidc_jwks_es256_key.pem
  oidc_jwks_rs256_key:
    file: secrets/oidc_jwks_rs256_key.pem
  session_secret:
    file: secrets/session_secret
  storage_encryption_key:
    file: secrets/storage_encryption_key
